server:
  port: 14000

spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/xiafengHYH/scc-test.git
          default-label: master

  application:
    name: "config-server"

  rabbitmq:
    stream:
      host: local
      port: 5672
      username: guest
      password: guest

  #暴露bus-refresh节点，通过此节点刷新配置
  management:
    endpoints:
      web:
        exposure:
          include: bus-refresh



eureka:
  instance:
    prefer-ip-address: true
    instance-id: "${spring.cloud.client.ip-address}:${server.port}"
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    service-url:
      defaultZone: "http://eurekaServer18000:18000/eureka/,http://eurekaServer18001:18001/eureka/"